# Generated by Django 5.1.6 on 2025-05-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOESApp', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slash_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
