# Generated by Django 5.1.6 on 2025-06-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOESApp', '0007_transaction_address_transaction_flw_transaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
