# Generated by Django 5.1.6 on 2025-06-09 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOESApp', '0009_color_size_remove_product_image_product_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Selected color for the cart item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='GOESApp.color'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(blank=True, help_text='Selected size for the cart item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='GOESApp.size'),
        ),
    ]
