# Generated by Django 5.1.6 on 2025-06-11 17:09

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('GOESApp', '0010_cartitem_color_cartitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=CKEditor5Field(blank=True, null=True),
        ),
    ]
