# Generated by Django 5.1.6 on 2025-07-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOESApp', '0012_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='homepage/')),
            ],
            options={
                'verbose_name': 'Home Page Images',
                'verbose_name_plural': 'Home Page Images',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
