# Generated by Django 5.1.6 on 2025-07-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOESApp', '0013_homepageimages_transaction_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
