# Generated by Django 5.1.6 on 2025-08-01 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOESApp', '0014_address_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GOESApp.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GOESApp.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GOESApp.size')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='GOESApp.transaction')),
            ],
        ),
    ]
